# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'XLAFNetworking' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for XLAFNetworking

  target 'XLAFNetworkingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'XLAFNetworkingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
pod 'FBMemoryProfiler'